:queues:
  - default
  - import # added
  - export # added

:max_retries: 5

development:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
