# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource Monograph`

---
attributes:
  monograph_title:
    type: string
    form:
      required: true
      primary: true
    index_keys:
      - "monograph_title_tesim"
      - "monograph_title_sim"
    predicate: http://hyrax-example.com/monograph_title
  record_info:
    type: string
    form:
      required: true
      primary: true
    index_keys:
      - "record_info_tesim"
      - "record_info_sim"
    predicate: http://hyrax-example.com/record_info
  place_of_publication:
    type: string
    form:
      required: false
      primary: true
    index_keys:
      - "place_of_publication_tesim"
      - "place_of_publication_sim"
    predicate: http://hyrax-example.com/place_of_publication
  genre:
    type: string
    form:
      primary: true
    index_keys:
      - "genre_tesim"
      - "genre_sim"
    predicate: http://hyrax-example.com/genre
  series_title:
    type: string
    form:
      primary: false
    index_keys:
      - "series_title_tesim"
      - "series_title_sim"
    predicate: http://hyrax-example.com/series_title
  target_audience:
    type: string
    form:
      multiple: true
    index_keys:
      - "target_audience_tesim"
      - "target_audience_sim"
    predicate: http://hyrax-example.com/target_audience
  table_of_contents:
    type: string
    form:
      multiple: false
    index_keys:
      - "table_of_contents_tesim"
      - "table_of_contents_sim"
    predicate: http://hyrax-example.com/table_of_contents
  date_of_issuance:
    type: string
    index_keys:
      - "date_of_issuance_tesim"
      - "date_of_issuance_sim"
    predicate: http://hyrax-example.com/date_of_issuance